# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LibTorch','1.8.0'

  # Pods for ios_client

end
